### ISSUE TITLE
Delete downloaded tracks which are not present anymore in the Spotify Playlist

### ISSUE THREAD

**Issue by ElStormus** [pjmeca/spotify-downloader#33]
Hello,

I think it would be interesting to add the functionality to delete music that is no longer present in the Spotify playlist automatically (by comparing the downloaded playlist with the one on the system, for example).

At the moment, I have to delete them by hand and remember which ones I've removed from my Spotify.

Thanks for the good work!

**Comment by pjmeca** [comment]
Hi! 👋

Thanks for the suggestion — it makes a lot of sense and would definitely improve the syncing experience.

I’m planning to support this by adding a new optional `mode` parameter in the tracking file, which will control how each playlist is handled:

```yml
- name: <playlist name>
  url: <spotify url>
  mode: <add | full> # defaults to 'add' if not specified
```

- `add`: only downloads new songs.
- `full`: syncs the playlist entirely, removing songs that no longer exist in the source playlist.

I'll start working on this soon!
